### ISSUE TITLE
测试了一下，网速很慢，而且不免流。。。

### ISSUE THREAD

**Issue by branchGit** [EraserCN/FuckUnicom#2]

**Comment by EraserCN** [comment]
检查您的联通营业厅里的免流信息（少部分地区无手厅直播免流），我这个是走的手厅直播（pull.free.video.10010.com）。你可以尝试修改v2ray host到免流地址

**Comment by branchGit** [comment]
> 检查您的联通营业厅里的免流信息（少部分地区无手厅直播免流），我这个是走的手厅直播（pull.free.video.10010.com）。你可以尝试修改v2ray host到免流地址

我的里面显示有个小沃直播，其他的还有手机电视，沃游戏，我视频，手机音乐，畅视，应该有那个host

**Comment by EraserCN** [comment]
用沃商店下面的音乐那个试试

**Comment by EraserCN** [comment]
music.hxll.wostore.cn

**Comment by EraserCN** [comment]
![IMG_20210521_131909](https://user-images.githubusercontent.com/79615365/119085886-24e6b880-ba37-11eb-97f4-2f6d7d8522c0.jpg)
网速没有问题

**Comment by branchGit** [comment]
> ![IMG_20210521_131909](https://user-images.githubusercontent.com/79615365/119085886-24e6b880-ba37-11eb-97f4-2f6d7d8522c0.jpg)
> 网速没有问题

好，我试试，这个网速跟我服务器网速有关是吗

**Comment by branchGit** [comment]
用沃音乐也不行，“之后强烈建议修改config.json之UUID”  这句是什么意思，怎么改，是不是因为我这个没改的原因？

**Comment by EraserCN** [comment]
不是，你不改也没问题。可以自己抓包看host地址。网速是你的问题了
